# @format
name: CI workflow to format, validate and plan terraform 
env:
  AWS_REGION: "us-west-2"

on:
  push:
    branches: 
      main
      

jobs:
  CI:
    name: "Global CI Workflow to format and validate terraform infrastructure"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        id: init
        working-directory: ./terraform
        run: |
          terraform init

      - name: Terraform Validate
        id: validate
        working-directory: ./terraform
        run: |
          terraform validate -no-color

      - name: Terraform Plan
        id: plan
        working-directory: ./terraform
        run: |
          terraform plan

      - name: Terraform Apply
        id: apply
        working-directory: ./terraform
        run: |
          terraform apply --auto-approve